import type { Metadata } from "next";

import { Noto_Sans } from "next/font/google";
import "./globals.css";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Вказуємо потрібні ваги
  style: ["normal", "italic"], // Вказуємо стилі
});

export const metadata: Metadata = {
  title: "My TOP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${notoSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
