import type { Metadata } from "next";
import style from "./Layout.module.css";
import { Noto_Sans } from "next/font/google";
import "./globals.css";

import { Footer, Header, Sidebar } from "@/layout";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Вказуємо потрібні ваги
  style: ["normal", "italic"], // Вказуємо стилі
});

export const metadata: Metadata = {
  title: "My TOP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.variable} ${style.body}`}>
        <div className={style.wrapper}>
          <Header className={style.header} />
          <Sidebar className={style.sidebar} />
          {children}
          <Footer className={style.footer} />
        </div>
      </body>
    </html>
  );
}
